version: "3.9"
services:
  matsim:
    build: .
    command:
    - config.xml
    - --config:controler.lastIteration
    - "10"
    environment:
      MATSIM_OUTPUT_OVERWRITE: "true"
      - JVM_OPTS=-Xmx12g -Xms12g -XX:MinRAMPercentage=75  -XX:MaxRAMPercentage=80
    volumes:
    - type: bind
      source: ${PWD}/test/input
      target: /opt/matsim/data/input
    - type: bind
      source: ${PWD}/test/output
      target: /opt/matsim/data/output
